### ISSUE TITLE
Line break in message

### ISSUE THREAD

**Issue by ralts00** [samknight/slack_applescript#10]
Hello, when I try to send a message of the style:

Super List:
- milk
- Cereal
- Beer

The script print:
Super List: - Milk- Cereal- Beer

When trying to use / n / r
I get very strange things, for example:
/ r generates a message for each line instead of just one.

How could I manage to send everything together in one message?

**Comment by ralts00** [comment]
Hello master @samknight , Can you think of any idea to send messages with line breaks?
Thanks :)

**Comment by samknight** [comment]
I've tried a few options but nothing has worked so far.  Have you managed to find a work around?

**Comment by ralts00** [comment]
I didn't find a way :(

**Comment by ralts00** [comment]
Why closed ?

**Comment by samknight** [comment]
Sorry was going to add a comment.

I’ve researched various methodologies for this and there is no possible that I can see to respect the line breaks in the code
