### ISSUE TITLE
Should /away be a toggle command

### ISSUE THREAD

**Issue by JeroenVdb** [samknight/slack_applescript#11]
At the moment "set as away" is a toggle command. Executing it will toggle the status between active and away.

This can be tricky if you don't know what your current Slack status is. For example when you run the command from Alfred without Slack focused.

To me it would be more explicit if away would always set yourself as away, independent of what your current status is. For example by first settings yourself to active `/active` (which is not a toggle command) and then to `/away`.

**Comment by samknight** [comment]
Hi, apologies for the delayed response to this. I'm currently rewriting the library to support the new shortcuts menu so will not be merging this as it will be superseded by the update. Thank you so much for contributing though

**Comment by samknight** [comment]
I've now added a new beta version. Please let me know id this resolves any issues you have https://github.com/samknight/slack_applescript/releases/tag/2.0.0-beta.1

**Comment by JeroenVdb** [comment]
This thread is more about a proposal to change the behavior of the away command.
With Slack the away command toggle the status between active and away. This way the command is not idempotent which makes it sometimes harder to use.
A solution could be to, when using slack_applescrips' away command, you first always set the user active and then away.

But then again, this would change the behavior that Slack offers and might confuse other people so I will close this one.
It it easily solvable in my script as well by doing:
```
tell script "Slack"
	send message "I'm AFK" in channel "#testjeroen"
	set as active
	set as away
end tell

```
