### ISSUE TITLE
Commands fail when cursor was left in "thread view"

### ISSUE THREAD

**Issue by cassus** [samknight/slack_applescript#13]
eg. when I leave my cursor in a thread input the app tries the type there, but slack replies:
`/open is not supported in threads. Sorry!`

**Comment by samknight** [comment]
I'm almost finished with a major update to support the new shortcuts that now exist in the interface. This will allow Open to work in threads as I will use cmd + k interface instead. I can't guarantee that other commands will work in this situation as there is no reliable way to refocus the cursor into the main channel input that I can find.

**Comment by samknight** [comment]
I've now added a new beta version. Please let me know id this resolves any issues you have https://github.com/samknight/slack_applescript/releases/tag/2.0.0-beta.1

**Comment by samknight** [comment]
I've made a ticket for a smoother way to do this but if you always start with an open channel command then it will refocus the text box. I've added a ticket to make this a bit smarter but will do what you need for now anyway.

https://github.com/samknight/slack_applescript/projects/1#card-50264694
