### ISSUE TITLE
error when focusing workspace

### ISSUE THREAD

**Issue by chrisvanpatten** [samknight/slack_applescript#18]
First and foremost, I love that you've put this together. Great stuff @samknight — this is going to be super valuable for an automation I'm building.

Second, I'm getting an issue on Big Sur when I run the `focus workspace` command:

<img width="812" alt="Screen Shot 2021-01-27 at 7 27 11 PM" src="https://user-images.githubusercontent.com/1231306/106072158-aa83d880-60d5-11eb-9655-53b8ac2cd20c.png">

From the error message, it looks like maybe it's expecting the workspace to be in the Window menu, however in my Slack app it's actually in `File → Workspace → {Workspace Name}`.

Otherwise though, it's been smooth sailing. Thanks again for releasing this!

**Comment by samknight** [comment]
Hi Chris, Apologies for the delay to this but I'm extremely thankful to you pointing out the error.

I have a temporary workaround without a release for you and that is to use the `Focus Channel` command but instead put in the name of the workspace.

I will try to complete a proper fix when I have a bit more time.

**Comment by samknight** [comment]
This is now fully fixed with the 2.0.1 release. Thank you for raising the error and apologies for the long turnaround time. Please re-open if this does not work as expected
