### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by joelmellon** [samknight/slack_applescript#20]
When I run
```
tell script "Slack"
   focus channel "general"
end tell
```
it occasionally works (maybe 10% of the time) but usually it pastes "general" into whatever channel I'm currently in (and sends it!) When it does work I can tell it's exec'ing `⌘+K` then types the channel into the "Jump to" input. (This is a hack I was using that's been buggy for me, so I was hoping slack_applescript was a better solution.)

Also, when I'm on a call `focus call window` does absolutely nothing, and the same with `focus main window`. I gave up trying other commands.

Slack Version: 4.16.2
samknight/slack_applescript version: 2.0.1

**Comment by samknight** [comment]
Hi Joel, 

Really sorry to hear this isn't working for you.

You've understood how this is working correctly. As this is 3rd party and there is nothing to hook into from the Slack app, everything inside is finely balanced hack and can break with any given update in slack.

If you want something more stable/reliable I would suggest looking at the libraries that use the API integration as a method of doing things. 

Alternatively if you look inside the AppleScript definitions you should be able to see all of the various methods that can be used directly e.g. `shortcut("open", "#general")` which allows customised use of the slash command and this particular method removes the use of cmd + k

I do test on my local machine every release and the commands given in your issue I have no issue with today but obviously there could be infinite differences between each Mac set up.

I hope you find something that works for your use case. Please let me know if I can assist further

**Comment by joelmellon** [comment]
Hey, thanks for the reply.

Do you know how I can look up the AppleScript definitions?

**Comment by samknight** [comment]
If you download the script and then open with Script Editor, you should be able to see the full source of the library
