### ISSUE TITLE
Hoping for listing workspaces and channels

### ISSUE THREAD

**Issue by ctwise** [samknight/slack_applescript#21]
Hello, first, thank you very much for creating this!

Second, is there any way to add support for listing workspaces and channels?

Thanks again!

**Comment by samknight** [comment]
Not currently but I think it should be straight forward to add the workspaces. I don't think channels will be possible though. How would you like the list of workspaces returned?

**Comment by ctwise** [comment]
Just JSON please.

**Comment by samknight** [comment]
Sorry I've had a fairly hectic summer. This is still on my list to add!

**Comment by samknight** [comment]
Going to close the issue for now but if I find a method of doing this, I'll add it to the roadmap. Thanks again for the suggestion
