### ISSUE TITLE
clear message box or warn before entering commands

### ISSUE THREAD

**Issue by jonblatho** [samknight/slack_applescript#32]
I'm not sure if this is even possible, but can a check be added to ensure that the message box is empty before attempting to enter a command, or could I be warned if it's not empty? I use this to simultaneously set myself as away/available on Slack and another application, and if I happen to have a message typed in the message box in Slack, this will send what I had typed with the command appended, like:

> Lorem ipsu/Set yourself as away

...which can be a bit embarrassing, particularly when the typed "message" happens to be just a space.

Anyway, it's a nice-to-have, not a need-to-have, for my forgetful moments. Thanks for this though, very nice being able to use AppleScript for this! I'm very inexperienced with AppleScript but would be happy to help out if there's anything I can do.

**Comment by henriquenunez** [comment]
Okay, just found out that the cmd + shift + y keystroke does the job for setting the status specifically

Imma try to change that

**Comment by samknight** [comment]
Hi both, ensuring the message box if focused as been a big headache for me, this adds an extra layer of complication. Would either of you run an experiment for me? Could you add these commands above the slack commands?


`tell application "Slack"
    activate
   keystroke "a" using command down
  delay 0.5
  key code 51
end tell
`

**Comment by henriquenunez** [comment]
Hello, I could just run it now. It does not really function properly. Another thing is that we need to call "System Events" to send `key code` and `keystroke` commands. So my quick fix was:

```
tell application "Slack"
	activate
	tell application "System Events"
		tell process "Slack" to keystroke "a" using command down
		tell process "Slack" to key code 51
	end tell
	delay 0.5
end tell
```

When I run it and I am inside a chat, with the checkbox selected, it selects whatever is inside the message box.
But in many other cases, like if I am just scrolling messages, it selects all the visible chat. (Let'sn't forget that slack uses electron)
We could try to force that the message box is selected maybe...

Another thing is: is there any possibility to prevent a desktop switch? It is super annoying to call this script via another automation tool (I use hammerspoon to do some weird behaviour that will set my slack status as the song I am listening to on spotify, I know it's unprofessional but lol) And whenever the song switches the desktop switches and it's annoying and a mess and my only dream was to have a discord like feature so i can show off my music... anyway)

At the time of writing I maybe came up with a solution:
- If you type / on slack it will open the prompt and you can type anything to send in the message box.
- But what it actually does is that it does not really send the message, it just focus the message box.
- We can then delete the N characters from the message box, select all, copy to a temp storage
- Send our actual slack command
- Restore the message box w/ the content of that temp storage.

What y'all think?

**Comment by samknight** [comment]
This seems to get things close but doesn't work if you're focused on a thread. Also cmd+a works for me once I've used `/` 

- type /
- escape
- cmd+x (to cut the existing text)
- do the message
- cmd+v

We could add that but with the caveat that this won't work for the main channel whilst your are in a thread
--

As for the desktop switch, due to electron app and non-first party support for these kind of scripts I don't think this will ever be possible. Very happy to be proven wrong though.

**Comment by henriquenunez** [comment]
Ok I just found out that you can exit the thread with option + up/down, which will also move you from the current channel.

**Comment by samknight** [comment]
I think I have found a combination that works.

```
arrow up
arrow left
arrow down
```

**Comment by samknight** [comment]
Hi all. I've gone with a different approach using the functions outlined in the 2.1.0 release

https://github.com/samknight/slack_applescript/releases/tag/2.1.0
