### ISSUE TITLE
Set as Away & Set as Active not working

### ISSUE THREAD

**Issue by Calligramien** [samknight/slack_applescript#36]
Hello guys, 

Hope you are doing all great.

I can't get the two commands to work: "set as away" and "set as active". When I run them, it sends messages in the conversation I'm in on Slack "= away" or "=active", depending on which command I run.

Here is my script: 

```
tell script "Slack"
	set as active
end tell
```

Thanks in advance and wish you all a great weekend ahead!

**Comment by samknight** [comment]
Hi @Calligramien Apologies for the delayed response. I think the linked PR will solve your issue but is not mergeable right now. 

I would only suspect that change to work if you have a different keyboard layout but there is a second issue where if you are already away and try to set your status as away, Slack has removed that option and therefore can't select it and it defaults to text. I suspect the latter is more your issue. I haven't yet found a solution to this.

**Comment by samknight** [comment]
I have implemented the suggested fix from #37 in the 2.0.3 release. Please give that a go and let me know if you have any issues
