### ISSUE TITLE
"Slack.zip" was removed in the latest commit

### ISSUE THREAD

**Issue by Daghall** [samknight/slack_applescript#42]
The installation instructions mentions unzipping a `Slack.zip` which was removed in [46ae102](https://github.com/samknight/slack_applescript/commit/46ae102df778d02334bfa6244a3df7a14570508e).

Is there a new way to install it, or do we need to resurrect this file? 🙂

**Comment by Daghall** [comment]
The README also refers to `src` which has also been removed (0dab7610).

**Comment by samknight** [comment]
Hi apologies for the confusion. The zip file is now in the releases section of GitHub can be accessed here https://github.com/samknight/slack_applescript/releases/tag/2.1.0

I hope that helps

**Comment by Daghall** [comment]
No worries. 🙂 

Is it the same contents as the repo?

Maybe update the README to reflect the changes, to avoid further confusion? 🙂

**Comment by samknight** [comment]
Yeah it's a good spot thank you. I need to make some updates with the new UI changes anyway so will update when I do that
