### ISSUE TITLE
Set "Do not disturb" not working for me

### ISSUE THREAD

**Issue by juliagarrigos** [samknight/slack_applescript#7]
Hi, 

I'm having issues setting the "do not disturb" mode.

When running:
```
tell script "Slack"
	focus workspace "myWorkspace"
	set do not disturb
end tell
```

I get the error: `Can’t make «script "Slack"» into type Unicode text.`

When running

```
tell script "Slack"
	focus workspace "myWorkspace"
	set do not disturb until 5pm
end tell
```

I get the error: `Expected end of line, etc. but found “until”.`

Am I doing something wrong or the commands are not working? 

Thanks!

**Comment by samknight** [comment]
Thanks for raising. I'm looking into it. 

From initial investigation it's not working as documented the below is a short term fix:

```set do not disturb "until 5pm"```

I need to fix both the optional parameter and removing the need for the parameter to have quote marks. Going to be on the look out for some AppleScript testing tools as well I think.

**Comment by samknight** [comment]
I believe this can be closed now  - there is possibly another related issue here which I'll keep open https://github.com/samknight/slack_applescript/issues/9
